# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 09:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturierApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('EnCour', 'En Cour'), ('Relance', 'A Relancer'), ('Valid', 'Valid')], default='EnCour', max_length=20),
        ),
        migrations.AlterField(
            model_name='linequotation',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
