# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturierApp', '0004_auto_20181012_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'permissions': (('view_task', 'Can see available tasks'),)},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': (('view_task', 'Can see available tasks'),)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('view_task', 'Can see available tasks'),)},
        ),
        migrations.AlterModelOptions(
            name='quotation',
            options={'permissions': (('view_task', 'Can see available tasks'),)},
        ),
    ]
