# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturierApp', '0005_auto_20181030_0815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': (('view', 'Can see available tasks'),)},
        ),
    ]
