# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturierApp', '0006_auto_20181030_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'permissions': (('view', 'Can see available tasks'),)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('view', 'Can see available tasks'),)},
        ),
        migrations.AlterModelOptions(
            name='quotation',
            options={'permissions': (('view', 'Can see available tasks'),)},
        ),
    ]
